version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build/

hooks:
  AfterInstall:
    - location: /home/ubuntu/scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: /home/ubuntu/scripts/restart_server.sh
      timeout: 60
      runas: root
